config/routes.rb
Rails.application.routes.draw do
    LOCALES = /en|pt\-BR/

    scope ":locale", :locale => LOCALES do
		get '/signup', to: 'users#new'
		get '/login', to: 'sessions#new'
		post '/login', to: 'sessions#create'
		delete '/logout', to: 'sessions#destroy'

	    resources :product_categories
		resources :users
		resources :sessions
		resources :products
	end

    match '/:locale' => 'home#index', :via => [:get], ':locale' => LOCALES
	root :to => "home#index"

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :product_category, optional: true

  validates_presence_of :name, :user_id
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	belongs_to :user
	has_many :products, dependent: :nullify

	validates_presence_of :name, :user_id
end

app/models/user.rb
class User < ApplicationRecord
	has_many :product_categories, dependent: :destroy
	has_many :products, dependent: :destroy

    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }

    has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		 												BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_filter :set_locale, :require_login

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
      { :locale => I18n.locale }
  end

  private

  def require_login
	  unless logged_in?
		  redirect_to login_url
	  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController

    def index
        @product_categories = get_sorted_categories
        @product_category_new = current_user.product_categories.new
    end

	def create
		@product_category_new = current_user.product_categories.new(category_params)
        if @product_category_new.save
			flash[:notice] = t('.success')
            redirect_to action: "index"
        else
			flash[:notice] = t('.error')
			@product_categories = get_sorted_categories
            render action: "index"
        end
	end

	def show
		flash[:notice] = ""
		redirect_to action: "index"
	end

    def update
		@product_category_edit = current_user.product_categories.find(params[:id])

		if @product_category_edit.update_attributes(category_params)
			flash[:notice] = t('.success')
			redirect_to action: "index"
		else
			@product_categories = get_sorted_categories
			@product_category_new = current_user.product_categories.new
			flash[:notice] = t('.error')
			render action: "index"
		end
    end

	def destroy
		@product_category = current_user.product_categories.find(params[:id])
		@product_category.destroy

		flash[:notice] = t('.success')
		redirect_to action: "index"
	end

	private

	def category_params
		params.require(:product_category).permit!
	end

	def get_sorted_categories
		return current_user.product_categories.all.sort_by {|f| f.name.downcase}
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = get_sorted_products
		@new_product = get_products.new
	end

	def create
		@new_product = get_products.new(product_params)

		if @new_product.save
			flash[:notice] = t('.success')
			redirect_to action: 'index'
		else
			flash[:notice] = t('.error')
			@products = get_sorted_products
			render action: 'index'
		end
	end

	def show
		flash[:notice] = nil
		redirect_to action: 'index'
	end

	def update
		@edit_product = get_products.find(params[:id])

		if @edit_product.update_attributes(product_params)
			flash[:notice] = t('.success')
			redirect_to action: 'index'
		else
			@products = get_sorted_products
			@new_product = get_products.new
			flash[:notice] = t('.error')
			render action: 'index'
		end
	end

	def destroy
		@product = get_products.find(params[:id])
		@product.destroy

		flash[:notice] = t('.success')
		redirect_to action: 'index'
	end

	private

	def product_params
		params.require(:product).permit!
	end

	def get_products
		return current_user.products
	end

	def get_sorted_products
		return get_products.all.sort_by {|f| f.name}
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_filter :require_login

  	def new
  	end

  	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to user
		else
			flash.now[:danger] = t('.error')
			render 'new'
		end
  	end

	def destroy
		log_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_filter :require_login, :only=>[:new,:create]

	def show
		@user = User.find(params[:id])
	end

  	def new
		@user = User.new
  	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = 'Welcome to the Sample App'
			redirect_to @user
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
									 :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/home/index.html.erb
<h1>Shopping List</h1>

<p>
    Escolha uma das ações a seguir:
    <ul>
        <li><%= link_to "Listar Categorias", product_categories_path %></li>
    </ul>
</p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar navbar-fixed-bottom navbar-inverse">
	<div class="container">
	  <small>
	    <%= link_to t('site.title'), root_path %>&copy; <%= t('footer.by') %> <a href="#">J. Carlos V. F.</a>
	  </small>
	  <nav>
	    <ul>
	      <li><%= link_to t('footer.about'),   '#' %></li>
	      <li><%= link_to t('footer.news'),   '#' %></li>
	    </ul>
	  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('header.logo'), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('header.home'), root_path %></li>
      <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('header.pages') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('product_categories.index.title'), product_categories_path %></li>
              <li><%= link_to t('products.index.title'), products_path %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('header.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('header.profile'), current_user %></li>
              <li><%= link_to t('header.settings'), '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t('header.logout'), logout_path, method: :delete %>
              </li>
            </ul>
          </li>

      <% else %>
          <li><%= link_to t('header.login'), login_path %></li>
          <li><%= link_to t('header.signup'), signup_path %></li>
      <% end %>

		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('header.language') %> <b class="caret"></b>
      </a>

			<ul class="dropdown-menu">
				<li><%= link_to image_tag('usa_flag', :class => 'flag_locale', :alt => t('header.usa.alt')), url_for(:locale => 'en') %></li>
				<li><%= link_to image_tag('brazilian_flag', :class => 'flag_locale', :alt => t('header.brazilian.alt')), url_for(:locale => 'pt-BR')%></li>
			</ul>
		</li>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t 'site.title' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<div id="mid_div">
    		<%= yield %>
		</div>

		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>

app/views/product_categories/_form.html.erb
<p>
	 <%= f.label :name %> * <br />
	 <%= f.text_field :name, :required => true %>
</p>
<p>
	 <%= f.label :description %> <br />
	 <%= f.text_area :description %>
</p>
<p>
	 <%= f.label :url_image %> <br />
	 <%= f.text_field :url_image %>
</p>
<p>
	 <%= f.submit %>
</p>

app/views/product_categories/index.html.erb
<%= render :layout => 'shared/default_page', :locals => { :translation_base => 'product_categories.index', :obj1 => @product_category_new, :obj2 => @product_category_edit, :objs => @product_categories, :path_to_form => 'product_categories/form' } do %>

    <tr>
        <th><%= t 'product_categories.index.name' %></th>
        <th><%= t 'product_categories.index.description' %></th>
		<th></th>
		<th></th>
    </tr>

    <% @product_categories.each do |product_category| %>
        <tr>
            <td> <%= product_category.name %> </td>
            <td> <%= product_category.description %> </td>
			<td>
				<%= render 'shared/default_page_button_edit', obj: product_category, edit_title: t('product_categories.index.button.edit') %>
			</td>
			<td>
				<%= render 'shared/default_page_button_delete', remove_text: t('product_categories.index.button.remove'), path_to_obj: product_category_path(product_category), confirm_text: t('general.confirm') %>
			</td>
        </tr>

    <% end %>

<% end %>

app/views/products/_form.html.erb
<p>
	 <%= f.label :name %> * <br />
	 <%= f.text_field :name, :required => true %>
</p>
<p>
	 <%= f.label :description %> <br />
	 <%= f.text_area :description %>
</p>
<p>
	 <%= f.label t('product_categories.index.name') %> <br />
	 <%= collection_select(:product, :product_category_id, current_user.product_categories.all.sort_by {|f| f.name}, :id, :name, :include_blank => true, :default => nil) %>
</p>
<p>
	 <%= f.submit %>
</p>

app/views/products/index.html.erb
<%= render :layout => 'shared/default_page', :locals => { :translation_base => 'products.index', :obj1 => @new_product, :obj2 => @edit_product, :objs => @products, :path_to_form => 'products/form' } do %>

    <tr>
        <th><%= t 'products.index.name' %></th>
        <th><%= t 'products.index.description' %></th>
		<th><%= t 'products.index.category' %></th>
		<th></th>
		<th></th>
    </tr>

    <% @products.each do |product| %>
        <tr>
            <td> <%= product.name %> </td>
            <td> <%= product.description %> </td>
			<td>
				<% if product.product_category_id != nil %>
				<%= ProductCategory.find(product.product_category_id).name %>
				<% end %>
			</td>
			<td>
				<%= render 'shared/default_page_button_edit', obj: product, edit_title: t('products.index.button.edit') %>
			</td>
			<td>
				<%= render 'shared/default_page_button_delete', remove_text: t('products.index.button.remove'), path_to_obj: product_path(product), confirm_text: t('general.confirm') %>
			</td>
        </tr>
    <% end %>

<% end %>

app/views/shared/_default_page.html.erb
<%= render 'shared/error_explanation', obj1: obj1, obj2: obj2 %>

<%= render 'shared/default_page_head', title: t(translation_base + '.title'), button_name: t(translation_base + '.button.new') %>

<div id="list_fixed">
    <table>
        <%= yield %>
    </table>
</div>

<%= render 'shared/default_page_newbox', create_title: t(translation_base + '.create.title'), warning_text: t(translation_base + '.warning'), obj: obj1, path_to_form: path_to_form %>

<%= render 'shared/default_page_edit_box', objs: objs, edit_title: t(translation_base + '.edit.title'), warning_text: t(translation_base + '.warning'), path_to_form: path_to_form %>

app/views/shared/_default_page_button_delete.html.erb
<div class="button" title="<%= remove_text %>" >
	<%= link_to remove_text, path_to_obj, method: :delete, data: { confirm: confirm_text } %>
</div>

app/views/shared/_default_page_button_edit.html.erb
<div class="button" onclick="<%= "editBoxOpen(" + obj.id.to_s + ")" %>" title="<%= edit_title %>" >
	<%= edit_title %>
</div>

app/views/shared/_default_page_edit_box.html.erb
<% objs.each do |obj| %>
<div id="<%= "edit_box_" + obj.id.to_s %>" class="edit_box" >
    <div id="<%= "edit_dialog_" + obj.id.to_s %>" class="edit_dialog">
		<a class="boxclose" onclick="<%= "editBoxClose(" + obj.id.to_s + ")" %>"></a>

		<b><%= edit_title %></b><br>
        <i><%= warning_text %></i>

        <%= form_for obj do |f| %>
            <%= render path_to_form, f: f %>
        <% end %>

    </div>
</div>
<% end %>

app/views/shared/_default_page_head.html.erb
<h1><%= title %></h1>

<div class="button" onclick="newBoxOpen()" title="<%= button_name %>" > <%= button_name %> </div>

app/views/shared/_default_page_newbox.html.erb
<div id="new_box">
    <div id="create_new_dialog">
		<a class="boxclose" onclick="newBoxClose()"></a>

        <b><%= create_title %></b><br>
        <i><%= warning_text %></i>

        <%= form_for obj do |f| %>
            <%= render path_to_form, f: f %>
        <% end %>

    </div>
</div>

app/views/shared/_error_explanation.html.erb
<% if obj1 != nil &&  obj1.errors.any? %>
	<%= render 'shared/error_explanation_item', obj: obj1 %>
<% end %>
<% if obj2 != nil && obj2.errors.any? %>
	<%= render 'shared/error_explanation_item', obj: obj2 %>
<% end %>

app/views/shared/_error_explanation_item.html.erb
<div id="error_explanation">
	<ul>
		<% obj.errors.full_messages.each do |message| %>
			<li> <%= message %></li>
		<% end %>
	</ul>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, 'error') %>
		</div>

		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1> <%= t '.title' %> </h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user)  do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, t('.password.confirmation') %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit t('.button.confirm'), class: "btn btn-primary" %>
		<% end %>
		<p> <%= t '.login.question' %> <%= link_to t('.login.title'), login_path %> </p>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="col-md-4">
		<section class="under_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>